version: '3.8'
services:
  dev-db:
    image: postgres:14.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: kimani
      POSTGRES_DB: nest
    networks:
      - kimani

networks:
  kimani:
